import '../models/kategori.dart';
import '../models/tukang.dart';
import '../models/user.dart';

class MockData {
  static final List<Kategori> kategoris = [
    Kategori(
      id: '1',
      nama: 'AC',
      icon: '❄️',
      deskripsi: 'Service AC, pasang AC, bongkar AC',
    ),
    Kategori(
      id: '2',
      nama: 'Listrik',
      icon: '⚡',
      deskripsi: 'Instalasi listrik, perbaikan, panel',
    ),
    Kategori(
      id: '3',
      nama: 'Ledeng',
      icon: '🔧',
      deskripsi: 'Pipa bocor, kran, saluran air',
    ),
    Kategori(
      id: '4',
      nama: 'Bangunan',
      icon: '🏗️',
      deskripsi: 'Renovasi, plester, cat, keramik',
    ),
    Kategori(
      id: '5',
      nama: 'Kebersihan',
      icon: '🧹',
      deskripsi: 'Cuci AC, bersihkan rumah, karpet',
    ),
    Kategori(
      id: '6',
      nama: 'Tukang Kayu',
      icon: '🪵',
      deskripsi: 'Furniture, lemari, kitchen set',
    ),
  ];

  static final List<Tukang> tukangs = [
    Tukang(
      id: '1',
      nama: 'Pak Budi',
      kategoriId: '1',
      deskripsi: 'Berpengalaman 15 tahun di bidang AC. Ahli service, pasang, dan bongkar semua merk AC.',
      skills: ['Service AC', 'Pasang AC', 'Cuci AC', 'Freon AC'],
      rating: 4.8,
      jumlahReview: 127,
      hargaMulai: 75000,
      lokasi: 'Kota Malang',
      jarak: 2.5,
      foto: 'https://i.pravatar.cc/150?img=1',
    ),
    Tukang(
      id: '2',
      nama: 'Mas Hendra',
      kategoriId: '1',
      deskripsi: 'Spesialis AC split dan central. Cepat, rapi, dan bergaransi.',
      skills: ['AC Split', 'AC Central', 'Pasang Baru', 'Cuci AC'],
      rating: 4.6,
      jumlahReview: 89,
      hargaMulai: 50000,
      lokasi: 'Kota Batu',
      jarak: 5.0,
      foto: 'https://i.pravatar.cc/150?img=2',
    ),
    Tukang(
      id: '3',
      nama: 'Pak Eko',
      kategoriId: '2',
      deskripsi: 'Teknisi listrik bersertifikat. Semua pekerjaan listrik rumah dan gedung.',
      skills: ['Instalasi Rumah', 'Panel Listrik', 'Perbaikan', 'Pasang Lampu'],
      rating: 4.9,
      jumlahReview: 203,
      hargaMulai: 100000,
      lokasi: 'Kota Malang',
      jarak: 1.8,
      foto: 'https://i.pravatar.cc/150?img=3',
    ),
    Tukang(
      id: '4',
      nama: 'Mas Rudi',
      kategoriId: '2',
      deskripsi: 'Spesialis listrik rumah tangga dan industri kecil. Cepat dan terpercaya.',
      skills: ['Perbaikan Instalasi', 'Pasang Stop Kontak', 'MCB', 'Grounding'],
      rating: 4.5,
      jumlahReview: 64,
      hargaMulai: 50000,
      lokasi: 'Kota Malang',
      jarak: 3.2,
      foto: 'https://i.pravatar.cc/150?img=4',
    ),
    Tukang(
      id: '5',
      nama: 'Pak Slamet',
      kategoriId: '3',
      deskripsi: 'Ahli pipa dan saluran air. Mengatasi kebocoran dengan cepat dan tepat.',
      skills: ['Pipa Bocor', 'Kran Air', 'Saluran Mampet', 'Water Heater'],
      rating: 4.7,
      jumlahReview: 156,
      hargaMulai: 50000,
      lokasi: 'Kota Malang',
      jarak: 4.0,
      foto: 'https://i.pravatar.cc/150?img=5',
    ),
    Tukang(
      id: '6',
      nama: 'Mas Agus',
      kategoriId: '3',
      deskripsi: 'Tukang ledeng berpengalaman 10 tahun. Kerja rapi dan bergaransi.',
      skills: ['Instalasi Pipa', 'Toilet', 'Shower', 'Tangki Air'],
      rating: 4.4,
      jumlahReview: 43,
      hargaMulai: 75000,
      lokasi: 'Kota Batu',
      jarak: 6.5,
      foto: 'https://i.pravatar.cc/150?img=6',
    ),
    Tukang(
      id: '7',
      nama: 'Pak Hartono',
      kategoriId: '4',
      deskripsi: 'Kontraktor bangunan 20 tahun pengalaman. Renovasi rumah dan gedung.',
      skills: ['Renovasi', 'Plester', 'Keramik', 'Cat Dinding'],
      rating: 4.9,
      jumlahReview: 312,
      hargaMulai: 150000,
      lokasi: 'Kota Malang',
      jarak: 2.0,
      foto: 'https://i.pravatar.cc/150?img=7',
    ),
    Tukang(
      id: '8',
      nama: 'Mas Yanto',
      kategoriId: '4',
      deskripsi: 'Spesialis finishing bangunan. Cat, plester, dan keramik berkualitas.',
      skills: ['Cat Interior', 'Plester Halus', 'Keramik', 'Acian'],
      rating: 4.6,
      jumlahReview: 88,
      hargaMulai: 100000,
      lokasi: 'Kota Malang',
      jarak: 3.5,
      foto: 'https://i.pravatar.cc/150?img=8',
    ),
    Tukang(
      id: '9',
      nama: 'Bu Sari',
      kategoriId: '5',
      deskripsi: 'Jasa kebersihan profesional untuk rumah dan kantor. Peralatan lengkap.',
      skills: ['Cuci AC', 'Bersihkan Rumah', 'Cuci Karpet', 'Fogging'],
      rating: 4.7,
      jumlahReview: 178,
      hargaMulai: 75000,
      lokasi: 'Kota Malang',
      jarak: 1.5,
      foto: 'https://i.pravatar.cc/150?img=9',
    ),
    Tukang(
      id: '10',
      nama: 'Pak Johan',
      kategoriId: '6',
      deskripsi: 'Tukang kayu profesional. Pembuatan furniture custom sesuai pesanan.',
      skills: ['Lemari', 'Kitchen Set', 'Meja Kursi', 'Rak'],
      rating: 4.8,
      jumlahReview: 145,
      hargaMulai: 200000,
      lokasi: 'Kota Batu',
      jarak: 7.0,
      foto: 'https://i.pravatar.cc/150?img=10',
    ),
    Tukang(
      id: '11',
      nama: 'Mas Dedi',
      kategoriId: '6',
      deskripsi: 'Ahli woodworking dengan sentuhan modern. Hasil rapi dan presisi.',
      skills: ['Interior Kayu', 'Partisi', 'Pintu', 'Jendela'],
      rating: 4.5,
      jumlahReview: 67,
      hargaMulai: 150000,
      lokasi: 'Kota Malang',
      jarak: 4.2,
      foto: 'https://i.pravatar.cc/150?img=11',
    ),
    Tukang(
      id: '12',
      nama: 'Mas Feri',
      kategoriId: '5',
      deskripsi: 'Layanan kebersihan lengkap dengan mesin industri. Hasil maksimal.',
      skills: ['Cuci Sofa', 'Cuci Springbed', 'Cuci Karpet', 'Sterilisasi'],
      rating: 4.6,
      jumlahReview: 94,
      hargaMulai: 100000,
      lokasi: 'Kota Malang',
      jarak: 2.8,
      foto: 'https://i.pravatar.cc/150?img=12',
    ),
  ];

  static List<Tukang> getTukangByKategori(String kategoriId) {
    return tukangs.where((t) => t.kategoriId == kategoriId).toList();
  }

  static Tukang? getTukangById(String id) {
    return tukangs.firstWhere((t) => t.id == id);
  }

  static final UserModel currentUser = UserModel(
    id: '1',
    nama: 'Pengguna',
    noHP: '0812-3456-7890',
    email: 'user@example.com',
  );
}
